version: "3"
services:
  redis:
    image: redis:5-alpine
    read_only: true
    restart: unless-stopped
    networks:
      - backend

  yog_sothoth:
    image: registry.rlab.be/sysadmins/yog_sothoth:latest
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /tmp
    depends_on:
      - redis
    networks:
      - backend
      - frontend
    env_file:
      - .env
    environment:
      - YOG_API_PREFIX=/api

  nginx:
    image: nginx:mainline-alpine
    read_only: true
    restart: unless-stopped
    tmpfs:
      - /run
      - /var/cache/nginx
    depends_on:
      - yog_sothoth
    networks:
      - frontend
    volumes:
      - ./nginx-vhost.conf:/etc/nginx/conf.d/yog_sothoth.conf:ro
    ports:
      - "127.0.0.1:80:80/tcp"

networks:
  frontend:

  backend:
